### ISSUE TITLE
Tooltip still active after restarting suspended server

### ISSUE THREAD

**Issue by adamkdean** [edge/account#193]
After restarting a suspended server (due to non-payment), the little tooltip remains active:

<img width="600" alt="image" src="https://github.com/edge/account/assets/1639527/56f9fb82-715c-4ffa-a81d-b9e9f8040f9b">

**Comment by willgarrett64** [comment]
@adamkdean this is because the unsuspend server job cycle is every 5 minutes, so after an account is unsupended there will be a short period before the server is also unsuspended.

What I've done is add a line that will unsuspend a server when the user manually starts their server. This should remove in turn remove the tooltip.

However, for automatic unsuspends, the user will have to wait until the next cycle. As I say, that's up to a max of 5 minutes.
